# Generated by Django 3.1.2 on 2020-10-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userm',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userm',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userm',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
