# Generated by Django 3.1.2 on 2020-10-13 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_auto_20201013_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
