# Generated by Django 3.1.2 on 2020-10-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_auto_20201019_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/LogoColor.JPG', null=True, upload_to='profile-pics'),
        ),
    ]
