# Generated by Django 3.1.4 on 2021-01-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0011_auto_20201209_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
        migrations.DeleteModel(
            name='UserM',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
