# Generated by Django 3.1.2 on 2020-10-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='/../../Logo.JPG', null=True, upload_to='profile-pics'),
        ),
    ]
